### ISSUE TITLE
Source / documentation

### ISSUE THREAD

**Issue by hirenj** [Nesvilab/philosopher#111]
Hi,

I'm planning on writing some post-processing software in golang, and am on the hunt for any libraries that I can use that can wrap up all of the best processes in manipulating spectral data.

I'm hoping that the code that you will soon be able to release for this project will be useful in that regard. Is there any chance that you have documentation for the object / class model available so that I can evaluate whether this will be useful for my purposes (or if I should just wrap one of the other C/C++ mass spec libraries in a golang wrapper!).

Cheers,

Hiren

**Comment by prvst** [comment]
As soon as our paper is out the entire code base will be available. Initially Philosopher was designed as an extendable library but that slowly changed to accommodate some of our needs for efficiency and speed. The code can still be extended and imported into your own, specially the packages dedicated to read  external formats. The documentation we have right now covers part of the code because its a work in progress. I suggest you keep an eye on the repo notifications and once it's available I would be more than happy to assist you.
