### ISSUE TITLE
msconvert erases home directory

### ISSUE THREAD

**Issue by blahoink** [Nesvilab/philosopher#47]
Just tried to use philosopher/msconvert on my computing cluster, and it completely erased my entire home folder. I had parts of it backed up so it's not that bad... but posting this so others don't run into the same problem.

OS: CentOS 7, with [slurm](https://slurm.schedmd.com/documentation.html) job manager

Command:

```
>$ srun ./philosopher_linux_amd64 msconvert /path/to/raw_file.raw
$ time="17:53:43" level=info msg="Executing Msconvert 20190319"
$ time="17:53:43" level=info msg=Done
```

... and then all my files are gone. I tested this twice and the same thing happened both times.

```
>$ ls -a
.  ..
```

Any idea why this is happening?

**Comment by prvst** [comment]
@blahoink 

That surely doesn't sound good at all, I'm sorry that this happened with you.

Did you created a workspace before trying to run msconvert ?
When you say home folder you mean the user home in `/home/` or the folder containing the data ?

I also noticed that you are running the Linux binary and trying to convert a raw file. If you read the program documentation [here](https://github.com/Nesvilab/philosopher/wiki/MSConvert), you will se that this is not possible.

**Comment by blahoink** [comment]
Yep, I know that most MS file converters don't read vendor raw files on Linux. I saw that there was the option and just went for it -- wishful thinking I guess.

I didn't know about having to create a workspace. I just got MSFragger working on a Windows machine and noticed that part in the tutorial. Again, should've read ahead ... but it still bad that the tool has the potential to erase files without user permission.

The program erased my entire home directory (```/home/<user>```). It also erased itself, which is weird.

**Comment by blahoink** [comment]
I guess the easiest fix would be to detect the OS, detect that the input file is a vendor RAW, and stop msconvert right then and there. That would do it, unless this bug extends past the msconvert sub-directive

**Comment by prvst** [comment]
You know, its been probably little more than a year since I added msconvert to Philosopher and about 3 years since the beginning of this project and this is the first time I hear about such behavior. Philosopher is developed on a Mint computer so problems like that can be easily avoided, and for sure never happened with us before

The msconvert command  implementation is a simple wrapper to the Linux binary provided by pwiz, so what Philosopher is doing is basically dispatching a system call to msconvert and passing the given parameters from the command line. I can't imagine how it is possible for the program to behave in such a manner. Nevertheless, this is not acceptable, I'll compile a new version still tonight with a workaround to the problem or even disabling the command, will see.

Again, I'm really sorry that this occurred to you.

**Comment by blahoink** [comment]
I debated whether to open this issue on msconvert but I remember that I tried the same thing on an msconvert binary a few months ago and while it failed it didnt do this. Not sure if thats relevant to this problem.

Not a big problem, like I said I had backups. Just trying to prevent the next one :)

**Comment by prvst** [comment]
fixed. msconvert will be unavailable for a while ntil we discover the cause of the problem.
