### ISSUE TITLE
PTMProphet: command "chmod 664 interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.mod.pep.xml" failed: Unknown error caused corrupted pep.xml and mod.pep.xml files

### ISSUE THREAD

**Issue by caberryhill** [Nesvilab/philosopher#479]
Hi, I'm currently running the TMT16 acetylation pipeline and am running into errors with ProteinProphet. 
Error:
pipe "C:\Users\causherm\AppData\Local\Temp\2\26110c68-9f75-4a9c-aaca-0b9cc4a9da31/DatabaseParser "C:\Users\causherm\Documents\MS_files\TNBC_TMT_Take2\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml"" failed: No error.

When I don't run ProteinProphet, the pipeline works seamlessly. Currently unsure of how to proceed as I don't know if this is an issue with ProteinProphet or an issue with an administratively locked computer (the temp file does have read, write, and execute permissions). Thank you for your help!

[log_2023-12-12_14-21-34.txt](https://github.com/Nesvilab/FragPipe/files/13662506/log_2023-12-12_14-21-34.txt)

**Comment by fcyu** [comment]
Could you please upload your mzML files, workflow files, and fasta files to https://www.dropbox.com/request/s52S2N2RwKGrdF3Z7eMN

Thanks,

Fengchao

**Comment by caberryhill** [comment]
Of note, I changed the TMT16 to TMT18 in the TMT Integrator. I uploaded the TMT annotation file as well.

**Comment by fcyu** [comment]
Hi @caberryhill ,

I can finish processing your file without any issue: 
[log_2023-12-13_14-42-49.txt](https://github.com/Nesvilab/philosopher/files/13665116/log_2023-12-13_14-42-49.txt)

The error you had may be due to the IO or file system. You probably need to troubleshoot it locally.

One thing I noticed is that you name two of the channels to "None". If you want to ignore those channels, you should name them "NA".

Best,

Fengchao

**Comment by caberryhill** [comment]
Gotcha, thank you so much for your time and help!

**Comment by caberryhill** [comment]
I contacted IT support and using administrative privileges, I was not able to successfully complete the pipeline. I also ran the regular TMT16 workflow which pipes the output of percolator to Proteinprophet, thus getting around the "chmod" error. I also redownloaded and installed all the config modules. However, I still received the same error related to running DatabaseParser.exe that can be seen at the end of the log file I attached in the initial issue.

I then ran proteinprophet from the command line, and that successfully processed the *.pepxml file, resulting in a prot.xml file. The rest of Philosopher could also be run from the command line. This then appears to be a Fragpipe specific issue. Do you have any suggestions for where to start looking in order to solve this?

**Comment by fcyu** [comment]
The "chmod" error was from PTMProphet. Have you ran that in your command line?

Best,

Fengchao

**Comment by caberryhill** [comment]
When I run PTMProphet in the command line, the error is still there. It writes the mod.pep.xml  file, but is unable to change it's permission. 

I had ran the TMT16 built-in workflow in Fragpipe without PTMProphet to see if the ProteinProphet error was due to the inability to change the permission of the output of PTMProphet. However, without PTMProphet, there is still the DatabaseParser.exe error. This error is not present when I run ProteinProphet from the command line. 

Are these then 2 separate errors?

**Comment by fcyu** [comment]
> When I run PTMProphet in the command line, the error is still there. It writes the mod.pep.xml file, but is unable to change it's permission.

Yes, that is the cause of the crash you observed. And that is also why I changed the title of this issue.

> I had ran the TMT16 built-in workflow in Fragpipe without PTMProphet to see if the ProteinProphet error was due to the inability to change the permission of the output of PTMProphet. However, without PTMProphet, there is still the DatabaseParser.exe error. This error is not present when I run ProteinProphet from the command line.

You must have messed up something. The order should always be PeptideProphet --> PTMProphet --> ProteinProphet, or PeptideProphet --> ProteinProphet. So, it does not make much sense to check if "ProteinProphet error was due to the inability to change the permission of the output of PTMProphet". If you want, I can take a look at your log.

> Are these then 2 separate errors?

Hard to tell given the limited information.

Best,

Fengchao

**Comment by fcyu** [comment]
> Yeah, so I've ran the TMT16 workflow in the past without ProteinProphet and gotten the chmod errors, and Fragpipe continued on to the next step, Philosopher Filter. It definitely doesn'tt change the permissions of each file, but the output files look ok? 

If you didn't run ProteinProphet, there will be no protein grouping (or the protein grouping is not accurate) in the final report.

> I ran percolator -> ProteinProphet. I used the percolator output file when I ran ProteinProphet in the command line.

If you replace PeptideProphet with Percolator, and don't run PTMProphet, the problem will go away because it is from PeptideProphet or PTMProphet.

>  I also tried to run Peptideprophet -> ProteinProphet in Fragpipe, and the DatabaseParser.exe issue is still present. 

That is because something was wrong when PeptideProphet was running:
```shell
model complete after 28 iterations
error: no peptideprophet data written to file C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml

command "mv -f "C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml.tmp.a12076" "C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml"" failed: Unknown error
failed to update C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml from temp file C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml.tmp.a12076, error 2 "No such file or directory"
command "mv -f "C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml.tmp.a12076" "C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml"" failed: Unknown error
failed to update C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml from temp file C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml.tmp.a12076, error 2 "No such file or directory"
command "mv -f "C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml.tmp.a12076" "C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml"" failed: Unknown error
failed to update C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml from temp file C:\Users\causherm\Documents\MS_files\Output\interact-2023_01_15_ExplorisFAIMS45_55_65_Cornett_F4.pep.xml.tmp.a12076, error 2 "
```

Again, those errors are still due to some file permission or IO issues. We never saw such weird error before. Since neither PeptideProphet nor PTMProphet was developed by us, I am not sure if I can help much regarding these errors.

Best,

Fengchao

**Comment by caberryhill** [comment]
Ah, I see now. That makes sense. Thank you so much for taking the time to explain it! I'll continue to try to figure out what is causing these weird errors.
